import 'package:flutter/material.dart';

class ListModel {
  final String? tittle,
      date,
      message,
      deliveryType,
      deliveryTime,
      image,
      modifyOrder,
      categories,
      dateTime,
      review,
      process,
      name,
      track,
      peopleExpression,
      sale,
      model,
      remove,
      brands,
      topSellings,
      express,
      newOrOld,
      currentPrice,
      oldPrice,
      rating,
      soldOutOrNot;
  final IconData? iconData;
  final int id;

  ListModel(
      {this.tittle,
      this.date,
      this.brands,
      this.deliveryTime,
      this.remove,
      this.modifyOrder,
      this.deliveryType,
      required this.id,
      this.peopleExpression,
      this.name,
      this.topSellings,
      this.sale,
      this.dateTime,
      this.categories,
      this.model,
      this.express,
      this.newOrOld,
      this.currentPrice,
      this.oldPrice,
      this.rating,
      this.soldOutOrNot,
      this.track,
      this.image,
      this.review,
      this.iconData,
      this.process,
      this.message});
}
List catagories =[
  ListModel(
      id: 1,
      sale: "-19% OFF",
      express: "EXPRESS",
      newOrOld: "New",
      categories: "Men Fashion",
      deliveryType: "Change Delivery Type",
      peopleExpression: "People want this",
      model: "APPLE IPHONE 13 PRO MAX - 6.7 APPLE IPHONE 13 PRO MAX - 6.7",
      currentPrice: "Rs 331,999",
      oldPrice: "Rs 331,999",
      topSellings: "GAMING",
      rating: "4.8",
      remove: "Remove",
      brands: "https://cdn.britannica.com/94/193794-050-0FB7060D/Adidas-logo.jpg",
      deliveryTime: "Free Delivery by",
      dateTime: "Tomorrow, Nov 26",
      soldOutOrNot: "10,000 Sold",
      name: "Furniture",
      modifyOrder: "Modify Order",
      tittle: "Special Offer on Casual Shirts",
      date: "10/12/21",
      image: "assets/images/cat_furniture.jpg",
      iconData: Icons.arrow_forward_ios,
      track: "Track Order",
      message:
      "Don't miss out on discount available just for you. Hurry! Shop Now.",
      review: "Write a Review",
      process: "Delivered"),
  ListModel(
      id: 2,
      sale: "-19% OFF",
      express: "EXPRESS",
      newOrOld: "New",
      categories: "Men Fashion",
      deliveryType: "Change Delivery Type",
      peopleExpression: "People want this",
      model: "APPLE IPHONE 13 PRO MAX - 6.7 APPLE IPHONE 13 PRO MAX - 6.7",
      currentPrice: "Rs 331,999",
      oldPrice: "Rs 331,999",
      topSellings: "GAMING",
      rating: "4.8",
      remove: "Remove",
      brands: "https://cdn.britannica.com/94/193794-050-0FB7060D/Adidas-logo.jpg",
      deliveryTime: "Free Delivery by",
      dateTime: "Tomorrow, Nov 26",
      soldOutOrNot: "10,000 Sold",
      name: "Shoes",
      modifyOrder: "Modify Order",
      tittle: "Special Offer on Casual Shirts",
      date: "10/12/21",
      image: "assets/images/cat_shoes.jpg",
      iconData: Icons.arrow_forward_ios,
      track: "Track Order",
      message:
      "Don't miss out on discount available just for you. Hurry! Shop Now.",
      review: "Write a Review",
      process: "Delivered"),
  ListModel(
      id: 3,
      sale: "-19% OFF",
      express: "EXPRESS",
      newOrOld: "New",
      categories: "Men Fashion",
      deliveryType: "Change Delivery Type",
      peopleExpression: "People want this",
      model: "APPLE IPHONE 13 PRO MAX - 6.7 APPLE IPHONE 13 PRO MAX - 6.7",
      currentPrice: "Rs 331,999",
      oldPrice: "Rs 331,999",
      topSellings: "GAMING",
      rating: "4.8",
      remove: "Remove",
      brands: "https://cdn.britannica.com/94/193794-050-0FB7060D/Adidas-logo.jpg",
      deliveryTime: "Free Delivery by",
      dateTime: "Tomorrow, Nov 26",
      soldOutOrNot: "10,000 Sold",
      name: "Clothes",
      modifyOrder: "Modify Order",
      tittle: "Special Offer on Casual Shirts",
      date: "10/12/21",
      image: "assets/images/cat_clothes.jpg",
      iconData: Icons.arrow_forward_ios,
      track: "Track Order",
      message:
      "Don't miss out on discount available just for you. Hurry! Shop Now.",
      review: "Write a Review",
      process: "Delivered"),
  ListModel(
      id: 4,
      sale: "-19% OFF",
      express: "EXPRESS",
      newOrOld: "New",
      categories: "Men Fashion",
      deliveryType: "Change Delivery Type",
      peopleExpression: "People want this",
      model: "APPLE IPHONE 13 PRO MAX - 6.7 APPLE IPHONE 13 PRO MAX - 6.7",
      currentPrice: "Rs 331,999",
      oldPrice: "Rs 331,999",
      topSellings: "GAMING",
      rating: "4.8",
      remove: "Remove",
      brands: "https://cdn.britannica.com/94/193794-050-0FB7060D/Adidas-logo.jpg",
      deliveryTime: "Free Delivery by",
      dateTime: "Tomorrow, Nov 26",
      soldOutOrNot: "10,000 Sold",
      name: "Phones",
      modifyOrder: "Modify Order",
      tittle: "Special Offer on Casual Shirts",
      date: "10/12/21",
      image: "assets/images/cat_phones.png",
      iconData: Icons.arrow_forward_ios,
      track: "Track Order",
      message:
      "Don't miss out on discount available just for you. Hurry! Shop Now.",
      review: "Write a Review",
      process: "Delivered"),
  ListModel(
      id: 5,
      sale: "-19% OFF",
      express: "EXPRESS",
      newOrOld: "New",
      categories: "Men Fashion",
      deliveryType: "Change Delivery Type",
      peopleExpression: "People want this",
      model: "APPLE IPHONE 13 PRO MAX - 6.7 APPLE IPHONE 13 PRO MAX - 6.7",
      currentPrice: "Rs 331,999",
      oldPrice: "Rs 331,999",
      topSellings: "GAMING",
      rating: "4.8",
      remove: "Remove",
      brands: "https://cdn.britannica.com/94/193794-050-0FB7060D/Adidas-logo.jpg",
      deliveryTime: "Free Delivery by",
      dateTime: "Tomorrow, Nov 26",
      soldOutOrNot: "10,000 Sold",
      name: "Watches",
      modifyOrder: "Modify Order",
      tittle: "Special Offer on Casual Shirts",
      date: "10/12/21",
      image: "assets/images/cat_watches.jpg",
      iconData: Icons.arrow_forward_ios,
      track: "Track Order",
      message:
      "Don't miss out on discount available just for you. Hurry! Shop Now.",
      review: "Write a Review",
      process: "Delivered"),
  ListModel(
      id: 6,
      sale: "-19% OFF",
      express: "EXPRESS",
      newOrOld: "New",
      categories: "Men Fashion",
      deliveryType: "Change Delivery Type",
      peopleExpression: "People want this",
      model: "APPLE IPHONE 13 PRO MAX - 6.7 APPLE IPHONE 13 PRO MAX - 6.7",
      currentPrice: "Rs 331,999",
      oldPrice: "Rs 331,999",
      topSellings: "GAMING",
      rating: "4.8",
      remove: "Remove",
      brands: "https://cdn.britannica.com/94/193794-050-0FB7060D/Adidas-logo.jpg",
      deliveryTime: "Free Delivery by",
      dateTime: "Tomorrow, Nov 26",
      soldOutOrNot: "10,000 Sold",
      name: "Beauty",
      modifyOrder: "Modify Order",
      tittle: "Special Offer on Casual Shirts",
      date: "10/12/21",
      image: "assets/images/cat_beauty.jpg",
      iconData: Icons.arrow_forward_ios,
      track: "Track Order",
      message:
      "Don't miss out on discount available just for you. Hurry! Shop Now.",
      review: "Write a Review",
      process: "Delivered"),
 ListModel(
      id: 7,
      sale: "-19% OFF",
      express: "EXPRESS",
      newOrOld: "New",
      categories: "Men Fashion",
      deliveryType: "Change Delivery Type",
      peopleExpression: "People want this",
      model: "APPLE IPHONE 13 PRO MAX - 6.7 APPLE IPHONE 13 PRO MAX - 6.7",
      currentPrice: "Rs 331,999",
      oldPrice: "Rs 331,999",
      topSellings: "GAMING",
      rating: "4.8",
      remove: "Remove",
      brands: "https://cdn.britannica.com/94/193794-050-0FB7060D/Adidas-logo.jpg",
      deliveryTime: "Free Delivery by",
      dateTime: "Tomorrow, Nov 26",
      soldOutOrNot: "10,000 Sold",
      name: "Lilly Queen",
      modifyOrder: "Modify Order",
      tittle: "Special Offer on Casual Shirts",
      date: "10/12/21",
      image: "assets/images/Image Popular Product 1.png",
      iconData: Icons.arrow_forward_ios,
      track: "Track Order",
      message:
      "Don't miss out on discount available just for you. Hurry! Shop Now.",
      review: "Write a Review",
      process: "Delivered"),

  ListModel(
      id: 8,
      sale: "-19% OFF",
      express: "EXPRESS",
      newOrOld: "New",
      categories: "Men Fashion",
      deliveryType: "Change Delivery Type",
      peopleExpression: "People want this",
      model: "APPLE IPHONE 13 PRO MAX - 6.7 APPLE IPHONE 13 PRO MAX - 6.7",
      currentPrice: "Rs 331,999",
      oldPrice: "Rs 331,999",
      topSellings: "GAMING",
      rating: "4.8",
      remove: "Remove",
      brands: "https://cdn.britannica.com/94/193794-050-0FB7060D/Adidas-logo.jpg",
      deliveryTime: "Free Delivery by",
      dateTime: "Tomorrow, Nov 26",
      soldOutOrNot: "10,000 Sold",
      name: "Lilly Queen",
      modifyOrder: "Modify Order",
      tittle: "Special Offer on Casual Shirts",
      date: "10/12/21",
      image: "assets/images/advancebtn.png",
      iconData: Icons.arrow_forward_ios,
      track: "Track Order",
      message:
      "Don't miss out on discount available just for you. Hurry! Shop Now.",
      review: "Write a Review",
      process: "Delivered"),
/*
  ListModel(
      id: 9,
      sale: "-19% OFF",
      express: "EXPRESS",
      newOrOld: "New",
      categories: "Men Fashion",
      deliveryType: "Change Delivery Type",
      peopleExpression: "People want this",
      model: "APPLE IPHONE 13 PRO MAX - 6.7 APPLE IPHONE 13 PRO MAX - 6.7",
      currentPrice: "Rs 331,999",
      oldPrice: "Rs 331,999",
      topSellings: "GAMING",
      rating: "4.8",
      remove: "Remove",
      brands: "https://cdn.britannica.com/94/193794-050-0FB7060D/Adidas-logo.jpg",
      deliveryTime: "Free Delivery by",
      dateTime: "Tomorrow, Nov 26",
      soldOutOrNot: "10,000 Sold",
      name: "Lilly Queen",
      modifyOrder: "Modify Order",
      tittle: "Special Offer on Casual Shirts",
      date: "10/12/21",
      image: "assets/images/advancebtn.png",
      iconData: Icons.arrow_forward_ios,
      track: "Track Order",
      message:
      "Don't miss out on discount available just for you. Hurry! Shop Now.",
      review: "Write a Review",
      process: "Delivered"),
  ListModel(
      id: 10,
      sale: "-19% OFF",
      express: "EXPRESS",
      newOrOld: "New",
      categories: "Men Fashion",
      deliveryType: "Change Delivery Type",
      peopleExpression: "People want this",
      model: "APPLE IPHONE 13 PRO MAX - 6.7 APPLE IPHONE 13 PRO MAX - 6.7",
      currentPrice: "Rs 331,999",
      oldPrice: "Rs 331,999",
      topSellings: "GAMING",
      rating: "4.8",
      remove: "Remove",
      brands: "https://cdn.britannica.com/94/193794-050-0FB7060D/Adidas-logo.jpg",
      deliveryTime: "Free Delivery by",
      dateTime: "Tomorrow, Nov 26",
      soldOutOrNot: "10,000 Sold",
      name: "Lilly Queen",
      modifyOrder: "Modify Order",
      tittle: "Special Offer on Casual Shirts",
      date: "10/12/21",
      image: "assets/images/advancebtn.png",
      iconData: Icons.arrow_forward_ios,
      track: "Track Order",
      message:
      "Don't miss out on discount available just for you. Hurry! Shop Now.",
      review: "Write a Review",
      process: "Delivered"),
  ListModel(
      id: 11,
      sale: "-19% OFF",
      express: "EXPRESS",
      newOrOld: "New",
      categories: "Men Fashion",
      deliveryType: "Change Delivery Type",
      peopleExpression: "People want this",
      model: "APPLE IPHONE 13 PRO MAX - 6.7 APPLE IPHONE 13 PRO MAX - 6.7",
      currentPrice: "Rs 331,999",
      oldPrice: "Rs 331,999",
      topSellings: "GAMING",
      rating: "4.8",
      remove: "Remove",
      brands: "https://cdn.britannica.com/94/193794-050-0FB7060D/Adidas-logo.jpg",
      deliveryTime: "Free Delivery by",
      dateTime: "Tomorrow, Nov 26",
      soldOutOrNot: "10,000 Sold",
      name: "Lilly Queen",
      modifyOrder: "Modify Order",
      tittle: "Special Offer on Casual Shirts",
      date: "10/12/21",
      image: "assets/images/advancebtn.png",
      iconData: Icons.arrow_forward_ios,
      track: "Track Order",
      message:
      "Don't miss out on discount available just for you. Hurry! Shop Now.",
      review: "Write a Review",
      process: "Delivered"),
  ListModel(
      id: 12,
      sale: "-19% OFF",
      express: "EXPRESS",
      newOrOld: "New",
      categories: "Men Fashion",
      deliveryType: "Change Delivery Type",
      peopleExpression: "People want this",
      model: "APPLE IPHONE 13 PRO MAX - 6.7 APPLE IPHONE 13 PRO MAX - 6.7",
      currentPrice: "Rs 331,999",
      oldPrice: "Rs 331,999",
      topSellings: "GAMING",
      rating: "4.8",
      remove: "Remove",
      brands: "https://cdn.britannica.com/94/193794-050-0FB7060D/Adidas-logo.jpg",
      deliveryTime: "Free Delivery by",
      dateTime: "Tomorrow, Nov 26",
      soldOutOrNot: "10,000 Sold",
      name: "Lilly Queen",
      modifyOrder: "Modify Order",
      tittle: "Special Offer on Casual Shirts",
      date: "10/12/21",
      image: "assets/images/advancebtn.png",
      iconData: Icons.arrow_forward_ios,
      track: "Track Order",
      message:
      "Don't miss out on discount available just for you. Hurry! Shop Now.",
      review: "Write a Review",
      process: "Delivered"),
  ListModel(
      id: 13,
      sale: "-19% OFF",
      express: "EXPRESS",
      newOrOld: "New",
      categories: "Men Fashion",
      deliveryType: "Change Delivery Type",
      peopleExpression: "People want this",
      model: "APPLE IPHONE 13 PRO MAX - 6.7 APPLE IPHONE 13 PRO MAX - 6.7",
      currentPrice: "Rs 331,999",
      oldPrice: "Rs 331,999",
      topSellings: "GAMING",
      rating: "4.8",
      remove: "Remove",
      brands: "https://cdn.britannica.com/94/193794-050-0FB7060D/Adidas-logo.jpg",
      deliveryTime: "Free Delivery by",
      dateTime: "Tomorrow, Nov 26",
      soldOutOrNot: "10,000 Sold",
      name: "Lilly Queen",
      modifyOrder: "Modify Order",
      tittle: "Special Offer on Casual Shirts",
      date: "10/12/21",
      image: "assets/images/advancebtn.png",
      iconData: Icons.arrow_forward_ios,
      track: "Track Order",
      message:
      "Don't miss out on discount available just for you. Hurry! Shop Now.",
      review: "Write a Review",
      process: "Delivered"),*/
];
List list = [
  ListModel(
      id: 1,
      sale: "-19% OFF",
      express: "EXPRESS",
      newOrOld: "New",
      categories: "Men Fashion",
      deliveryType: "Change Delivery Type",
      peopleExpression: "People want this",
      model: "APPLE IPHONE 13 PRO MAX - 6.7 APPLE IPHONE 13 PRO MAX - 6.7",
      currentPrice: "Rs 331,999",
      oldPrice: "Rs 331,999",
      topSellings: "GAMING",
      rating: "4.8",
      remove: "Remove",
      brands: "https://cdn.britannica.com/94/193794-050-0FB7060D/Adidas-logo.jpg",
      deliveryTime: "Free Delivery by",
      dateTime: "Tomorrow, Nov 26",
      soldOutOrNot: "10,000 Sold",
      name: "Lilly Queen",
      modifyOrder: "Modify Order",
      tittle: "Special Offer on Casual Shirts",
      date: "10/12/21",
      image: "assets/images/Image Popular Product 1.png",
      iconData: Icons.arrow_forward_ios,
      track: "Track Order",
      message:
          "Don't miss out on discount available just for you. Hurry! Shop Now.",
      review: "Write a Review",
      process: "Delivered"),
  ListModel(
      id: 2,
      sale: "-150% OFF",
      express: "EXPRESS",
      modifyOrder: "Modify Order",
      brands: "https://cdn.britannica.com/94/193794-050-0FB7060D/Adidas-logo.jpg",
      newOrOld: "New",
      deliveryType: "Change Delivery Type",
      peopleExpression: "People want this",
      model: "APPLE IPHONE 13 PRO MAX - 6.7 APPLE IPHONE 13 PRO MAX - 6.7",
      currentPrice: "Rs 331,999",
      categories: "Women Fashion",
      oldPrice: "Rs 331,999",
      topSellings: "GAMING",
      remove: "Remove",
      rating: "4.8",
      deliveryTime: "Free Delivery by",
      dateTime: "Tomorrow, Nov 26",
      soldOutOrNot: "50,000 Sold",
      name: "Lilly Queen",
      tittle: "Special Offer on Casual Shirts",
      date: "10/12/21",
      image: "assets/images/Image Popular Product 1.png",
      iconData: Icons.arrow_forward_ios,
      track: "Track Order",
      message:
          "Don't miss out on discount available just for you. Hurry! Shop Now.",
      review: "Write a Review",
      process: "Delivered"),
  ListModel(
      id: 3,
      sale: "-17% OFF",
      express: "EXPRESS",
      newOrOld: "New",
      categories: "Men Fashion",
      brands: "https://cdn.britannica.com/94/193794-050-0FB7060D/Adidas-logo.jpg",
      deliveryType: "Change Delivery Type",
      peopleExpression: "People want this",
      model: "APPLE IPHONE 13 PRO MAX - 6.7 APPLE IPHONE 13 PRO MAX - 6.7",
      currentPrice: "Rs 331,999",
      oldPrice: "Rs 331,999",
      topSellings: "GAMING",
      rating: "4.8",
      remove: "Remove",
      deliveryTime: "Free Delivery by",
      dateTime: "Tomorrow, Nov 26",
      soldOutOrNot: "10,000 Sold",
      name: "Lilly Queen",
      modifyOrder: "Modify Order",
      tittle: "Special Offer on Casual Shirts",
      date: "10/12/21",
      image: "assets/images/Image Popular Product 1.png",
      iconData: Icons.arrow_forward_ios,
      track: "Track Order",
      message:
          "Don't miss out on discount available just for you. Hurry! Shop Now.",
      review: "Write a Review",
      process: "Delivered"),
  ListModel(
      id: 4,
      sale: "-17% OFF",
      express: "EXPRESS",
      modifyOrder: "Modify Order",
      brands: "https://cdn.britannica.com/94/193794-050-0FB7060D/Adidas-logo.jpg",
      newOrOld: "New",
      deliveryType: "Change Delivery Type",
      peopleExpression: "People want this",
      model: "APPLE IPHONE 13 PRO MAX - 6.7 APPLE IPHONE 13 PRO MAX - 6.7",
      currentPrice: "Rs 331,999",
      categories: "Women Fashion",
      oldPrice: "Rs 331,999",
      topSellings: "GAMING",
      remove: "Remove",
      rating: "4.8",
      deliveryTime: "Free Delivery by",
      dateTime: "Tomorrow, Nov 26",
      soldOutOrNot: "10,000 Sold",
      name: "Lilly Queen",
      tittle: "Special Offer on Casual Shirts",
      date: "10/12/21",
      image: "assets/images/Image Popular Product 1.png",
      iconData: Icons.arrow_forward_ios,
      track: "Track Order",
      message:
          "Don't miss out on discount available just for you. Hurry! Shop Now.",
      review: "Write a Review",
      process: "Delivered"),
  ListModel(
      id: 5,
      sale: "-17% OFF",
      express: "EXPRESS",
      newOrOld: "New",
      categories: "Men Fashion",
      brands: "https://cdn.britannica.com/94/193794-050-0FB7060D/Adidas-logo.jpg",
      deliveryType: "Change Delivery Type",
      peopleExpression: "People want this",
      model: "APPLE IPHONE 13 PRO MAX - 6.7 APPLE IPHONE 13 PRO MAX - 6.7",
      currentPrice: "Rs 331,999",
      oldPrice: "Rs 331,999",
      topSellings: "GAMING",
      rating: "4.8",
      remove: "Remove",
      deliveryTime: "Free Delivery by",
      dateTime: "Tomorrow, Nov 26",
      soldOutOrNot: "10,000 Sold",
      name: "Lilly Queen",
      modifyOrder: "Modify Order",
      tittle: "Special Offer on Casual Shirts",
      date: "10/12/21",
      image: "assets/images/Image Popular Product 1.png",
      iconData: Icons.arrow_forward_ios,
      track: "Track Order",
      message:
          "Don't miss out on discount available just for you. Hurry! Shop Now.",
      review: "Write a Review",
      process: "Delivered"),
  ListModel(
      id: 6,
      sale: "-17% OFF",
      express: "EXPRESS",
      modifyOrder: "Modify Order",
      newOrOld: "New",
      deliveryType: "Change Delivery Type",
      peopleExpression: "People want this",
      model: "APPLE IPHONE 13 PRO MAX - 6.7 APPLE IPHONE 13 PRO MAX - 6.7",
      currentPrice: "Rs 331,999",
      categories: "Women Fashion",
      oldPrice: "Rs 331,999",
      topSellings: "GAMING",
      remove: "Remove",
      brands: "https://cdn.britannica.com/94/193794-050-0FB7060D/Adidas-logo.jpg",
      rating: "4.8",
      deliveryTime: "Free Delivery by",
      dateTime: "Tomorrow, Nov 26",
      soldOutOrNot: "10,000 Sold",
      name: "Lilly Queen",
      tittle: "Special Offer on Casual Shirts",
      date: "10/12/21",
      image: "assets/images/Image Popular Product 1.png",
      iconData: Icons.arrow_forward_ios,
      track: "Track Order",
      message:
          "Don't miss out on discount available just for you. Hurry! Shop Now.",
      review: "Write a Review",
      process: "Delivered"),
  ListModel(
      id: 7,
      sale: "-17% OFF",
      express: "EXPRESS",
      newOrOld: "New",
      categories: "Men Fashion",
      deliveryType: "Change Delivery Type",
      peopleExpression: "People want this",
      model: "APPLE IPHONE 13 PRO MAX - 6.7 APPLE IPHONE 13 PRO MAX - 6.7",
      currentPrice: "Rs 331,999",
      oldPrice: "Rs 331,999",
      topSellings: "GAMING",
      rating: "4.8",
      remove: "Remove",
      deliveryTime: "Free Delivery by",
      brands: "https://cdn.britannica.com/94/193794-050-0FB7060D/Adidas-logo.jpg",
      dateTime: "Tomorrow, Nov 26",
      soldOutOrNot: "10,000 Sold",
      name: "Lilly Queen",
      modifyOrder: "Modify Order",
      tittle: "Special Offer on Casual Shirts",
      date: "10/12/21",
      image: "assets/images/Image Popular Product 1.png",
      iconData: Icons.arrow_forward_ios,
      track: "Track Order",
      message:
          "Don't miss out on discount available just for you. Hurry! Shop Now.",
      review: "Write a Review",
      process: "Delivered"),
  ListModel(
      id: 8,
      sale: "-17% OFF",
      express: "EXPRESS",
      modifyOrder: "Modify Order",
      newOrOld: "New",
      deliveryType: "Change Delivery Type",
      peopleExpression: "People want this",
      model: "APPLE IPHONE 13 PRO MAX - 6.7 APPLE IPHONE 13 PRO MAX - 6.7",
      currentPrice: "Rs 331,999",
      categories: "Women Fashion",
      oldPrice: "Rs 331,999",
      topSellings: "GAMING",
      remove: "Remove",
      rating: "4.8",
      deliveryTime: "Free Delivery by",
      dateTime: "Tomorrow, Nov 26",
      soldOutOrNot: "10,000 Sold",
      name: "Lilly Queen",
      tittle: "Special Offer on Casual Shirts",
      brands: "https://cdn.britannica.com/94/193794-050-0FB7060D/Adidas-logo.jpg",
      date: "10/12/21",
      image: "assets/images/Image Popular Product 1.png",
      iconData: Icons.arrow_forward_ios,
      track: "Track Order",
      message:
          "Don't miss out on discount available just for you. Hurry! Shop Now.",
      review: "Write a Review",
      process: "Delivered"),
  ListModel(
      id: 9,
      sale: "-17% OFF",
      express: "EXPRESS",
      newOrOld: "New",
      categories: "Men Fashion",
      deliveryType: "Change Delivery Type",
      peopleExpression: "People want this",
      model: "APPLE IPHONE 13 PRO MAX - 6.7 APPLE IPHONE 13 PRO MAX - 6.7",
      currentPrice: "Rs 331,999",
      oldPrice: "Rs 331,999",
      brands: "https://cdn.britannica.com/94/193794-050-0FB7060D/Adidas-logo.jpg",
      topSellings: "GAMING",
      rating: "4.8",
      remove: "Remove",
      deliveryTime: "Free Delivery by",
      dateTime: "Tomorrow, Nov 26",
      soldOutOrNot: "10,000 Sold",
      name: "Lilly Queen",
      modifyOrder: "Modify Order",
      tittle: "Special Offer on Casual Shirts",
      date: "10/12/21",
      image: "assets/images/Image Popular Product 1.png",
      iconData: Icons.arrow_forward_ios,
      track: "Track Order",
      message:
          "Don't miss out on discount available just for you. Hurry! Shop Now.",
      review: "Write a Review",
      process: "Delivered"),
  ListModel(
      id: 10,
      sale: "-17% OFF",
      express: "EXPRESS",
      modifyOrder: "Modify Order",
      newOrOld: "New",
      deliveryType: "Change Delivery Type",
      brands: "https://cdn.britannica.com/94/193794-050-0FB7060D/Adidas-logo.jpg",
      peopleExpression: "People want this",
      model: "APPLE IPHONE 13 PRO MAX - 6.7 APPLE IPHONE 13 PRO MAX - 6.7",
      currentPrice: "Rs 331,999",
      categories: "Women Fashion",
      oldPrice: "Rs 331,999",
      topSellings: "GAMING",
      remove: "Remove",
      rating: "4.8",
      deliveryTime: "Free Delivery by",
      dateTime: "Tomorrow, Nov 26",
      soldOutOrNot: "10,000 Sold",
      name: "Lilly Queen",
      tittle: "Special Offer on Casual Shirts",
      date: "10/12/21",
      image: "assets/images/Image Popular Product 1.png",
      iconData: Icons.arrow_forward_ios,
      track: "Track Order",
      message:
          "Don't miss out on discount available just for you. Hurry! Shop Now.",
      review: "Write a Review",
      process: "Delivered"),
  ListModel(
      id: 11,
      sale: "-17% OFF",
      express: "EXPRESS",
      newOrOld: "New",
      categories: "Men Fashion",
      deliveryType: "Change Delivery Type",
      peopleExpression: "People want this",
      brands: "https://cdn.britannica.com/94/193794-050-0FB7060D/Adidas-logo.jpg",
      model: "APPLE IPHONE 13 PRO MAX - 6.7 APPLE IPHONE 13 PRO MAX - 6.7",
      currentPrice: "Rs 331,999",
      oldPrice: "Rs 331,999",
      topSellings: "GAMING",
      rating: "4.8",
      remove: "Remove",
      deliveryTime: "Free Delivery by",
      dateTime: "Tomorrow, Nov 26",
      soldOutOrNot: "10,000 Sold",
      name: "Lilly Queen",
      modifyOrder: "Modify Order",
      tittle: "Special Offer on Casual Shirts",
      date: "10/12/21",
      image: "assets/images/Image Popular Product 1.png",
      iconData: Icons.arrow_forward_ios,
      track: "Track Order",
      message:
          "Don't miss out on discount available just for you. Hurry! Shop Now.",
      review: "Write a Review",
      process: "Delivered"),
  ListModel(
      id: 12,
      sale: "-17% OFF",
      express: "EXPRESS",
      modifyOrder: "Modify Order",
      newOrOld: "New",
      deliveryType: "Change Delivery Type",
      peopleExpression: "People want this",
      model: "APPLE IPHONE 13 PRO MAX - 6.7 APPLE IPHONE 13 PRO MAX - 6.7",
      currentPrice: "Rs 331,999",
      brands: "https://cdn.britannica.com/94/193794-050-0FB7060D/Adidas-logo.jpg",
      categories: "Women Fashion",
      oldPrice: "Rs 331,999",
      topSellings: "GAMING",
      remove: "Remove",
      rating: "4.8",
      deliveryTime: "Free Delivery by",
      dateTime: "Tomorrow, Nov 26",
      soldOutOrNot: "10,000 Sold",
      name: "Lilly Queen",
      tittle: "Special Offer on Casual Shirts",
      date: "10/12/21",
      image: "assets/images/Image Popular Product 1.png",
      iconData: Icons.arrow_forward_ios,
      track: "Track Order",
      message:
          "Don't miss out on discount available just for you. Hurry! Shop Now.",
      review: "Write a Review",
      process: "Delivered"),
  ListModel(
      id: 13,
      sale: "-17% OFF",
      express: "EXPRESS",
      newOrOld: "New",
      categories: "Men Fashion",
      deliveryType: "Change Delivery Type",
      peopleExpression: "People want this",
      model: "APPLE IPHONE 13 PRO MAX - 6.7 APPLE IPHONE 13 PRO MAX - 6.7",
      currentPrice: "Rs 331,999",
      oldPrice: "Rs 331,999",
      topSellings: "GAMING",
      rating: "4.8",
      remove: "Remove",
      deliveryTime: "Free Delivery by",
      dateTime: "Tomorrow, Nov 26",
      soldOutOrNot: "10,000 Sold",
      name: "Lilly Queen",
      modifyOrder: "Modify Order",
      tittle: "Special Offer on Casual Shirts",
      date: "10/12/21",
      image: "assets/images/Image Popular Product 1.png",
      iconData: Icons.arrow_forward_ios,
      track: "Track Order",
      brands: "https://cdn.britannica.com/94/193794-050-0FB7060D/Adidas-logo.jpg",
      message:
          "Don't miss out on discount available just for you. Hurry! Shop Now.",
      review: "Write a Review",
      process: "Delivered"),
  ListModel(
      id: 14,
      sale: "-17% OFF",
      express: "EXPRESS",
      modifyOrder: "Modify Order",
      brands: "https://cdn.britannica.com/94/193794-050-0FB7060D/Adidas-logo.jpg",
      newOrOld: "New",
      deliveryType: "Change Delivery Type",
      peopleExpression: "People want this",
      model: "APPLE IPHONE 13 PRO MAX - 6.7 APPLE IPHONE 13 PRO MAX - 6.7",
      currentPrice: "Rs 331,999",
      categories: "Women Fashion",
      oldPrice: "Rs 331,999",
      topSellings: "GAMING",
      remove: "Remove",
      rating: "4.8",
      deliveryTime: "Free Delivery by",
      dateTime: "Tomorrow, Nov 26",
      soldOutOrNot: "10,000 Sold",
      name: "Lilly Queen",
      tittle: "Special Offer on Casual Shirts",
      date: "10/12/21",
      image: "assets/images/Image Popular Product 1.png",
      iconData: Icons.arrow_forward_ios,
      track: "Track Order",
      message:
          "Don't miss out on discount available just for you. Hurry! Shop Now.",
      review: "Write a Review",
      process: "Delivered"),
];

List Catagories =[
  ListModel(id: 1,
    categories: "Just For You",),
  ListModel(id: 2,
    categories: "Men Fashion",),
  ListModel(id: 3,
    categories: "Women Fashion",),
  ListModel(id: 4,
    categories: "Kids Fashion",),
  ListModel(id: 5,
    categories: "Beauty Fashion",),
  ListModel(id: 6,
    categories: "Watches Fashion",)
];

List BootaTopPicks =[
  ListModel(id: 1,
  categories: "Mens Fashion",
  image: "assets/images/men'sfashion.jpg"),
  ListModel(id: 2,
      categories: "Women's Fashion",
      image: "assets/images/womenfashion.jpg"),
  ListModel(id: 3,
      categories: "Kid's Fashion",
      image: "assets/images/kidsFaashion.jpg"),
  ListModel(id: 4,
      categories: "Mobiles",
      image: "assets/images/cat_phones.png"),
  ListModel(id: 5,
      categories: "Electronic Accessories",
      image: "assets/images/electronicfashion.jpg"),
  ListModel(id: 6,
      categories: "Video Games",
      image: "assets/images/videogames.jpg"),
  ListModel(id: 7,
      categories: "Fragrance",
      image: "assets/images/fragrance.jpg"),
  ListModel(id: 9,
      categories: "Skin Care",
      image: "assets/images/skincare.jpg"),
  ListModel(id: 10,
      categories: "Makeup",
      image: "assets/images/makeup.jpg"),
  ListModel(id: 11,
      categories: "Laptops",
      image: "assets/images/cat_laptops.png"),
  ListModel(id: 12,
      categories: "Home & Kitchen",
      image: "assets/images/homekitchen.jpg"),
  ListModel(id: 13,
      categories: "Televisions",
      image: "assets/images/television.jpg"),
  ListModel(id: 14,
      categories: "Appliances",
      image: "assets/images/appliance.jpg"),
  ListModel(id: 15,
      categories: "Baby Accessories",
      image: "assets/images/baby.jpg"),
  ListModel(id: 16,
  categories: "Toys & Games",
      image: "assets/images/toys.jpg"),
];

List brands=[
  ListModel(id: 1,
      categories: "NIKE",
      image: "assets/images/nikebrands.jpg"),
  ListModel(id: 2,
      categories: "ADIDAS",
      image: "assets/images/adidas.jpg"),
  ListModel(id: 3,
      categories: "JACK&JONES",
      image: "assets/images/jackjones.jpg"),
  ListModel(id: 4,
      categories: "PUMA",
      image: "assets/images/puma.jpg"),
  ListModel(id: 5,
      categories: "OUTFITTER",
      image: "assets/images/cat_clothes.jpg"),
  ListModel(id: 6,
      categories: "HUGOBOSS",
      image: "assets/images/hugoboss.jpg"),
];

List wardrobes=[
  ListModel(id: 1,
      categories: "T-shirt & polos",
      image: "assets/images/shirt.jpg"),
  ListModel(id: 2,
      categories: "Trousers",
      image: "assets/images/Trousers.jpg"),
  ListModel(id: 3,
      categories: "Sportswear",
      image: "assets/images/sportwear.jpg"),
  ListModel(id: 4,
      categories: "Sports shoes",
      image: "assets/images/cat_shoes.jpg"),
  ListModel(id: 5,
      categories: "Sneakers",
      image: "assets/images/sneakers.jpg"),
  ListModel(id: 6,
      categories: "Bags",
      image: "assets/images/bags.jpg"),
];
List mensshopcatagory=[
  ListModel(id: 1,
      categories: "T-shirt",
      image: "assets/images/shirt.jpg"),
  ListModel(id: 2,
      categories: "Polos",
      image: "assets/images/shirt.jpg"),
  ListModel(id: 3,
      categories: "Trousers",
      image: "assets/images/Trousers.jpg"),
  ListModel(id: 4,
      categories: "Sportswear",
      image: "assets/images/sportwear.jpg"),
  ListModel(id: 5,
      categories: "Sports shoes",
      image: "assets/images/cat_shoes.jpg"),
  ListModel(id: 6,
      categories: "Sneakers",
      image: "assets/images/sneakers.jpg"),
  ListModel(id: 7,
      categories: "Bags",
      image: "assets/images/bags.jpg"),
  ListModel(id: 8,
    categories: "Bags",
    image: "assets/images/bags.jpg"),
];
